# Generated by Django 3.2 on 2021-05-23 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfirstapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseOrg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=32, verbose_name='用户名')),
                ('avatar', models.ImageField(default='', upload_to='picture/', verbose_name='头像')),
            ],
        ),
    ]
