# Generated by Django 3.2 on 2021-05-24 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfirstapp', '0006_alter_attention_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='avatar',
            field=models.ImageField(default='', upload_to='picture/', verbose_name='头像'),
        ),
    ]
