# Generated by Django 3.2 on 2021-05-25 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfirstapp', '0008_alter_comment_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attention',
            name='account',
            field=models.ManyToManyField(blank=True, null=True, related_name='attend', to='myfirstapp.Account'),
        ),
    ]
