# Generated by Django 3.2 on 2021-05-25 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myfirstapp', '0009_alter_attention_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attention',
            old_name='account',
            new_name='accounts',
        ),
    ]
